### ISSUE TITLE
implement .render

### ISSUE THREAD

**Issue by tunnckoCore** [jstransformers/jstransformer-engine#1]
because the caching
https://github.com/jonschlinkert/engine/blob/master/index.js#L283

**Comment by RobLoach** [comment]
No... `.render` implements usage of `.compile` based on if the options/locals are different. By having JSTransformer use `.compile`, then the application can cache the compiled template itself, allowing different locals using the same pre-compiled template.

Well, if this is in addition to compile rather than replacing it, perhaps... It's usually always better to use `.compile`, and then use the built template instead of always calling `.render`.
